### BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

### calibrationParse.py
### Autogenerated by firmware-libraries/SerialComms/python/calibration_file_generator.py on Mon Aug  9 00:35:42 2021

import time
import struct

class PressurizationControllerCalibrations:

	def __init__(self):
		self.packet_byte_size = 48
		self.num_items = 26
		
		self.dict = {}
		self.units = {}
		
		self.items = [''] * self.num_items
		self.items[0] = 'packet_type'
		self.items[1] = 'origin_addr'
		self.items[2] = 'target_addr'
		self.items[3] = 'priority'
		self.items[4] = 'num_packets'
		self.items[5] = 'do_cobbs'
		self.items[6] = 'checksum'
		self.items[7] = 'timestamp'
		self.items[8] = 'pt_cal_lower_voltage[0]' 
		self.items[9] = 'pt_cal_lower_voltage[1]' 
		self.items[10] = 'pt_cal_lower_voltage[2]' 
		self.items[11] = 'pt_cal_lower_voltage[3]' 
		self.items[12] = 'pt_cal_lower_voltage[4]' 
		self.items[13] = 'pt_cal_lower_voltage[5]' 
		self.items[14] = 'pt_cal_upper_voltage[0]' 
		self.items[15] = 'pt_cal_upper_voltage[1]' 
		self.items[16] = 'pt_cal_upper_voltage[2]' 
		self.items[17] = 'pt_cal_upper_voltage[3]' 
		self.items[18] = 'pt_cal_upper_voltage[4]' 
		self.items[19] = 'pt_cal_upper_voltage[5]' 
		self.items[20] = 'pt_cal_upper_pressure[0]' 
		self.items[21] = 'pt_cal_upper_pressure[1]' 
		self.items[22] = 'pt_cal_upper_pressure[2]' 
		self.items[23] = 'pt_cal_upper_pressure[3]' 
		self.items[24] = 'pt_cal_upper_pressure[4]' 
		self.items[25] = 'pt_cal_upper_pressure[5]' 

		self.units[self.items[0]] = "ul"
		self.units[self.items[1]] = "ul"
		self.units[self.items[2]] = "ul"
		self.units[self.items[3]] = "ul"
		self.units[self.items[4]] = "ul"
		self.units[self.items[5]] = "ul"
		self.units[self.items[6]] = "ul"
		self.units[self.items[7]] = "ul"
		self.units[self.items[8]] = "V"
		self.units[self.items[9]] = "V"
		self.units[self.items[10]] = "V"
		self.units[self.items[11]] = "V"
		self.units[self.items[12]] = "V"
		self.units[self.items[13]] = "V"
		self.units[self.items[14]] = "V"
		self.units[self.items[15]] = "V"
		self.units[self.items[16]] = "V"
		self.units[self.items[17]] = "V"
		self.units[self.items[18]] = "V"
		self.units[self.items[19]] = "V"
		self.units[self.items[20]] = "psi"
		self.units[self.items[21]] = "psi"
		self.units[self.items[22]] = "psi"
		self.units[self.items[23]] = "psi"
		self.units[self.items[24]] = "psi"
		self.units[self.items[25]] = "psi"

	def parse_packet(self, packet):
		self.dict[self.items[0]] = int((float(struct.unpack("<B", packet[0:1])[0]))/1)
		self.dict[self.items[1]] = int((float(struct.unpack("<B", packet[1:2])[0]))/1)
		self.dict[self.items[2]] = int((float(struct.unpack("<B", packet[2:3])[0]))/1)
		self.dict[self.items[3]] = int((float(struct.unpack("<B", packet[3:4])[0]))/1)
		self.dict[self.items[4]] = int((float(struct.unpack("<B", packet[4:5])[0]))/1)
		self.dict[self.items[5]] = int((float(struct.unpack("<B", packet[5:6])[0]))/1)
		self.dict[self.items[6]] = int((float(struct.unpack("<H", packet[6:8])[0]))/1)
		self.dict[self.items[7]] = int((float(struct.unpack("<I", packet[8:12])[0]))/1)
		self.dict[self.items[8]] = float((float(struct.unpack("<h", packet[12:14])[0]))/10)
		self.dict[self.items[9]] = float((float(struct.unpack("<h", packet[14:16])[0]))/10)
		self.dict[self.items[10]] = float((float(struct.unpack("<h", packet[16:18])[0]))/10)
		self.dict[self.items[11]] = float((float(struct.unpack("<h", packet[18:20])[0]))/10)
		self.dict[self.items[12]] = float((float(struct.unpack("<h", packet[20:22])[0]))/10)
		self.dict[self.items[13]] = float((float(struct.unpack("<h", packet[22:24])[0]))/10)
		self.dict[self.items[14]] = float((float(struct.unpack("<h", packet[24:26])[0]))/10)
		self.dict[self.items[15]] = float((float(struct.unpack("<h", packet[26:28])[0]))/10)
		self.dict[self.items[16]] = float((float(struct.unpack("<h", packet[28:30])[0]))/10)
		self.dict[self.items[17]] = float((float(struct.unpack("<h", packet[30:32])[0]))/10)
		self.dict[self.items[18]] = float((float(struct.unpack("<h", packet[32:34])[0]))/10)
		self.dict[self.items[19]] = float((float(struct.unpack("<h", packet[34:36])[0]))/10)
		self.dict[self.items[20]] = int((float(struct.unpack("<h", packet[36:38])[0]))/1)
		self.dict[self.items[21]] = int((float(struct.unpack("<h", packet[38:40])[0]))/1)
		self.dict[self.items[22]] = int((float(struct.unpack("<h", packet[40:42])[0]))/1)
		self.dict[self.items[23]] = int((float(struct.unpack("<h", packet[42:44])[0]))/1)
		self.dict[self.items[24]] = int((float(struct.unpack("<h", packet[44:46])[0]))/1)
		self.dict[self.items[25]] = int((float(struct.unpack("<h", packet[46:48])[0]))/1)
