### BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

### _s2InterfaceAutogen.py
### Autogenerated by firmware-libraries/SerialComms/python/cmd_file_generator.py on Sat Jan  9 21:34:22 2021

import serial

class _S2_InterfaceAutogen:
	def __init__(self):
		# A dictionary mapping command name to packet_type (command ID)
		self.cmd_names_dict = {
			"set_vlv"	:	8,
			"send_telem_short"	:	9,
			"send_telem_all"	:	10,
			"set_stepper_period"	:	11,
			"set_stepper_direction"	:	12,
			"set_kp"	:	13,
			"set_ki"	:	14,
			"set_kd"	:	15,
			"set_control_calc_period"	:	16,
			"set_state"	:	17,
			"move_stepper_degrees"	:	18
		}

		# A dictionary mapping packet_type (command ID) to a list of function argument information.
		# The nth tuple in each list corresponds to the nth argument for that command's function,
		# in the order (arg_name, arg_type, xmit_scale)
		self.cmd_args_dict = {
			8	:	[('vlv_num', 'uint32_t', 1), ('state', 'uint8_t', 1)],
			9	:	[('board_num', 'uint8_t', 1)],
			10	:	[('board_num', 'uint8_t', 1)],
			11	:	[('stepper_num', 'uint8_t', 1), ('period', 'uint16_t', 1)],
			12	:	[('stepper_num', 'uint8_t', 1)],
			13	:	[('motor_num', 'uint8_t', 1), ('gain', 'double', 100)],
			14	:	[('motor_num', 'uint8_t', 1), ('gain', 'double', 100)],
			15	:	[('motor_num', 'uint8_t', 1), ('gain', 'double', 100)],
			16	:	[('period', 'uint16_t', 1)],
			17	:	[('state', 'uint8_t', 1)],
			18	:	[('motor_num', 'uint8_t', 1), ('deg', 'uint16_t', 1)]
		}

	"""
	Encodes command info and arguments with COBS and transmits them over serial
	@params
		ser (pyserial object)  - serial obejct to write to
		cmd_info (dict)        - dictionary with the following key value pairs:
			"function_name" : function name (string)
			"target_board_addr" : address of board to send command to (integer)
			"timestamp" : time the command was sent (integer)
			"args" : list of arguments to send to the function (list)
	"""
	def s2_command(self, ser, cmd_info):
		#Initialize empty packet
		packet = [0]*253  # Will add packet delimiters later to make it 255 bytes

		#Fill first 11 bytes of packet with CLB packet header information
		packet[0] = self.cmd_names_dict[cmd_info["function_name"]]	# packet_type
		packet[1] = cmd_info["target_board_addr"]	# target_addr
		packet[2] = 1	# priority
		packet[3] = 1	# num_packets
		packet[4] = 1	# do_cobbs
		packet[5] = 0	# checksum
		packet[6] = 0	# checksum
		packet[7] = (cmd_info["timestamp"] >> 0) & 0xFF	# timestamp
		packet[8] = (cmd_info["timestamp"] >> 8) & 0xFF	# timestamp
		packet[9] = (cmd_info["timestamp"] >> 16) & 0xFF	# timestamp
		packet[10] = (cmd_info["timestamp"] >> 24) & 0xFF	# timestamp

		# Stuff packet with the function arguments according to the packet_type ID
		command_id = self.cmd_names_dict[cmd_info["function_name"]]
		# set_vlv()
		if (command_id == 8):
			# vlv_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			packet[12] = (int(cmd_info["args"][0]*1) >> 8) & 0xFF
			packet[13] = (int(cmd_info["args"][0]*1) >> 16) & 0xFF
			packet[14] = (int(cmd_info["args"][0]*1) >> 24) & 0xFF
			# state
			packet[15] = (int(cmd_info["args"][1]*1) >> 0) & 0xFF
		# send_telem_short()
		elif (command_id == 9):
			# board_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
		# send_telem_all()
		elif (command_id == 10):
			# board_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
		# set_stepper_period()
		elif (command_id == 11):
			# stepper_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			# period
			packet[12] = (int(cmd_info["args"][1]*1) >> 0) & 0xFF
			packet[13] = (int(cmd_info["args"][1]*1) >> 8) & 0xFF
		# set_stepper_direction()
		elif (command_id == 12):
			# stepper_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
		# set_kp()
		elif (command_id == 13):
			# motor_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			# gain
			packet[12] = (int(cmd_info["args"][1]*100) >> 0) & 0xFF
			packet[13] = (int(cmd_info["args"][1]*100) >> 8) & 0xFF
			packet[14] = (int(cmd_info["args"][1]*100) >> 16) & 0xFF
			packet[15] = (int(cmd_info["args"][1]*100) >> 24) & 0xFF
			packet[16] = (int(cmd_info["args"][1]*100) >> 32) & 0xFF
			packet[17] = (int(cmd_info["args"][1]*100) >> 40) & 0xFF
			packet[18] = (int(cmd_info["args"][1]*100) >> 48) & 0xFF
			packet[19] = (int(cmd_info["args"][1]*100) >> 56) & 0xFF
		# set_ki()
		elif (command_id == 14):
			# motor_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			# gain
			packet[12] = (int(cmd_info["args"][1]*100) >> 0) & 0xFF
			packet[13] = (int(cmd_info["args"][1]*100) >> 8) & 0xFF
			packet[14] = (int(cmd_info["args"][1]*100) >> 16) & 0xFF
			packet[15] = (int(cmd_info["args"][1]*100) >> 24) & 0xFF
			packet[16] = (int(cmd_info["args"][1]*100) >> 32) & 0xFF
			packet[17] = (int(cmd_info["args"][1]*100) >> 40) & 0xFF
			packet[18] = (int(cmd_info["args"][1]*100) >> 48) & 0xFF
			packet[19] = (int(cmd_info["args"][1]*100) >> 56) & 0xFF
		# set_kd()
		elif (command_id == 15):
			# motor_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			# gain
			packet[12] = (int(cmd_info["args"][1]*100) >> 0) & 0xFF
			packet[13] = (int(cmd_info["args"][1]*100) >> 8) & 0xFF
			packet[14] = (int(cmd_info["args"][1]*100) >> 16) & 0xFF
			packet[15] = (int(cmd_info["args"][1]*100) >> 24) & 0xFF
			packet[16] = (int(cmd_info["args"][1]*100) >> 32) & 0xFF
			packet[17] = (int(cmd_info["args"][1]*100) >> 40) & 0xFF
			packet[18] = (int(cmd_info["args"][1]*100) >> 48) & 0xFF
			packet[19] = (int(cmd_info["args"][1]*100) >> 56) & 0xFF
		# set_control_calc_period()
		elif (command_id == 16):
			# period
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			packet[12] = (int(cmd_info["args"][0]*1) >> 8) & 0xFF
		# set_state()
		elif (command_id == 17):
			# state
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
		# move_stepper_degrees()
		elif (command_id == 18):
			# motor_num
			packet[11] = (int(cmd_info["args"][0]*1) >> 0) & 0xFF
			# deg
			packet[12] = (int(cmd_info["args"][1]*1) >> 0) & 0xFF
			packet[13] = (int(cmd_info["args"][1]*1) >> 8) & 0xFF

		# Encode the packet with COBS
		self.stuff_array(packet)

		# Write the bytes to serial
		ser.write(bytes(packet))

	"""
	Takes in a byte packet and return a COBS encoded version
	Note: this was copied directly from the EC3 gui code
	@params
		arr (integer array)  - Byte packet to be COBS encoded
		separator (integer)  - Packet delimiter. Should be using 0, but has the option to use any number
	"""
	def stuff_array(self, arr, separator=0):
		arr.append(0)
		arr.insert(0, 0)
		first_sep = 1
		for x in arr[1:]:
			if x == separator:
				break
			first_sep += 1
		index = 1
		while(index < len(arr)-1):
			if(arr[index] == separator):
				offset = 1
				while(arr[index+offset] != separator):
					offset += 1
				arr[index] = offset
				index += offset
			else:
				index += 1
		arr[0] = first_sep
		return arr

